### ISSUE TITLE
The expression of an export assignment must be an identifier or qualified name in an ambient context.

### ISSUE THREAD

**Issue by ChurikiTenna** [ol-th/pdf-img-convert.js#24]
Hi, I am trying to use the module with typescript.
Installed via `yarn add`.

However, it shows this error on pdf-img-convert.d.ts:
Line 15: export = { convert }
`The expression of an export assignment must be an identifier or qualified name in an ambient context.`

Am I misunderstanding some behaviors?

**Comment by ol-th** [comment]
I think this might be relevant here:
https://stackoverflow.com/questions/47094210/d-ts-not-compiling-after-typescript-2-6-1
