### ISSUE TITLE
TS compabilty -> .then does not exist | not so useless - useless await

### ISSUE THREAD

**Issue by BannukDE** [ol-th/pdf-img-convert.js#25]
First example definitly not running with ts:
Property 'then' does not exist on type '(string | Uint8Array)[]'.ts(2339)

Second example runs, once we enter some var declarations:
'await' has no effect on the type of this expression.ts(80007)

So here my little fix to your d.ts file:
Line 13 -> ```): Promise<string[]|Uint8Array[]>```

As you correctly mentioned your async function returns a resolveable Promise, we have to tell that ts.

Thanks for your work and sharing!

**Comment by ol-th** [comment]
Thanks for the suggestion, this will be added to the next release :)
