### ISSUE TITLE
Dependencies are too large

### ISSUE THREAD

**Issue by ilyai** [ol-th/pdf-img-convert.js#37]
I tried to use the package in an AWS Lambda but couldn't deploy it because, when extracted, function code combined with layers exceeds the maximum allowed size.
I've checked that after installation of this package `./node_modules/` grows by more than 120Mb, which seems quite a lot.
Is it possible to reduce it?

**Comment by ol-th** [comment]
I've whitelisted only the essential files to be included from npm. Hopefully this helps with your issue.
